handle case of error after running container

diff --git a/.github/workflows/postgresql.yml b/.github/workflows/postgresql.yml
--- a/.github/workflows/postgresql.yml
+++ b/.github/workflows/postgresql.yml
@@ -58,9 +58,7 @@ jobs:
             else
               echo "PostgreSQL container starting with name 'postgresql'."
               # Wait for PostgreSQL to be ready
-              until docker logs postgresql 2>&1 | { grep -E -qi 'ready' && exit 0; false; }; 
-                do sleep 1; 
-              done
+              until docker logs postgresql 2>&1 | { grep -E -qi 'ready' && exit 0; grep -E -qi 'error' && exit 1; false; }; do sleep 1; done
 
               echo "PostgreSQL container started"
 
